services:
    nginx:
        container_name: nginx
        build:
            context: nginx
        networks: 
            - backend-network
        ports:
            - "80:80"
        volumes:
            - type: bind
              source: ${PWD}/www
              target: /var/www
        links:
            - php
        restart: unless-stopped

    php:
        container_name: php8.3
        build:
            context: php/8.3
        networks: 
            - backend-network
        volumes:
            - type: bind
              source: ${PWD}/www
              target: /var/www
        ports:
            - "9000:9000"
        restart: unless-stopped

networks:
    backend-network: