services:
    nginx:
        container_name: nginx
        build:
            context: nginx
        networks: 
            - backend-network
            - frontend-network
        ports:
            - "80:80"
        volumes:
            - type: bind
              source: ${PWD}/www
              target: /var/www
        links:
            - php
        restart: unless-stopped

    php:
        container_name: php8.3
        build:
            context: php/8.3
        networks: 
            - backend-network
        volumes:
            - ${PWD}/www:/var/www
        ports:
            - "9000:9000"
        restart: unless-stopped

    mysql:
        container_name: db
        build:
            context: mysql/8.0
        volumes:
            - db:/var/lib/mysql
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: bitrix
            MYSQL_USER: bitrix
            MYSQL_PASSWORD: 123
            MYSQL_ROOT_PASSWORD: 123
            TZ: Europe/Moscow
        command: mysqld --user=root --sql-mode=""
        networks:
            - backend-network
        stdin_open: true
        tty: true
        restart: unless-stopped

    rabbitmq:
        container_name: rabbitmq
        build:
            context: rabbitmq
        ports:
            - "15672:15672"
        networks: 
            - frontend-network
            - backend-network
        links:
            - nginx
            - php
            - mysql
        environment:
            - RABBITMQ_DEFAULT_USER=rmuser
            - RABBITMQ_DEFAULT_PASS=rmpassword
            - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
        hostname: rabbitmq
        volumes:
            - rabbitmq:/var/lib/rabbitmq
        restart: always

    frontend:
        container_name: frontend
        build:
            context: .
            dockerfile: frontend/dockerfile
        ports:
            - "3000:3000"
        networks: 
            - frontend-network
        volumes:
            - type: bind
              source: ${PWD}/www/frontend
              target: /web
            - node_modules:/web/node_modules
        links:
            - nginx
            - php
            - mysql
        restart: unless-stopped
        tmpfs: /tmp

networks:
    backend-network:
    frontend-network:

volumes:
    db:
    node_modules:
    rabbitmq: