FROM phpdockerio/php:8.3-fpm

# USER bitrix
# RUN usermod -u 1000 bitrix

WORKDIR "/var/www"

COPY ./php.ini /etc/php/8.3/fpm/conf.d/90-php.ini
COPY ./php.ini /etc/php/8.3/cli/conf.d/90-php.ini

EXPOSE 9000